#ifndef __CONFIG_H
#define __CONFIG_H

#include <buttons.h>
#include <stdio.h>

// #define ZOROBOT3_A 1
#define ZOROBOT3_B 2

/** Laberinto */
#define CELL_DIMENSION 180
#define CELL_DIAGONAL 127.3
#define WALL_WIDTH 12
#define MIDDLE_MAZE_DISTANCE ((CELL_DIMENSION - WALL_WIDTH) / 2.)
#define SENSING_POINT_DISTANCE 20

/** Características Físicas */
#ifdef ZOROBOT3_A
#define MICROMETERS_PER_TICK 9.4967
#endif
#ifdef ZOROBOT3_B
#define MICROMETERS_PER_TICK 9.1901
#endif
#define ROBOT_FRONT_LENGTH 51.30
#define ROBOT_BACK_LENGTH 37.64
#define ROBOT_WIDTH 70
#define WHEELS_SEPARATION 60
#define ROBOT_MIDDLE_WIDTH ((ROBOT_WIDTH / 2.0))

/** Movimiento */
#define MAX_MOTOR_SATURATION_COUNT 20
#define BASE_LINEAR_ACCEL 3000
#define KP_LINEAR 0.0002
#define KI_LINEAR 0.0009
#define KD_LINEAR 0.00

// #define KP_ANGULAR 0.2
// #define KI_ANGULAR 0.007
// #define KD_ANGULAR 0.00

#define KP_ANGULAR 0.003
#define KI_ANGULAR 0.0
#define KD_ANGULAR 0.2

#define KP_SIDE_SENSORS 0.02
#define KI_SIDE_SENSORS 0.00025
#define KD_SIDE_SENSORS 0.00

#define KP_FRONT_SENSORS 0.0125
#define KI_FRONT_SENSORS 0.001
#define KD_FRONT_SENSORS 0.00

/** Sensores */
#define SENSOR_LOW_PASS_FILTER_ALPHA 0.1

#ifdef ZOROBOT3_A
#define SENSOR_FRONT_LEFT_WALL_OFFSET 0
#define SENSOR_FRONT_RIGHT_WALL_OFFSET 0
#define SENSOR_SIDE_LEFT_WALL_OFFSET -250
#define SENSOR_SIDE_RIGHT_WALL_OFFSET 0

#define SENSOR_FRONT_LEFT_WALL_SLOPE -0.0477
#define SENSOR_FRONT_LEFT_WALL_INTERCEPT 410
#define SENSOR_FRONT_RIGHT_WALL_SLOPE -0.0522
#define SENSOR_FRONT_RIGHT_WALL_INTERCEPT 450
#define SENSOR_SIDE_LEFT_WALL_SLOPE -0.0565
#define SENSOR_SIDE_LEFT_WALL_INTERCEPT 463
#define SENSOR_SIDE_RIGHT_WALL_SLOPE -0.0606
#define SENSOR_SIDE_RIGHT_WALL_INTERCEPT 482
#endif

#ifdef ZOROBOT3_B
#define SENSOR_FRONT_LEFT_WALL_OFFSET 0
#define SENSOR_FRONT_RIGHT_WALL_OFFSET 0
#define SENSOR_SIDE_LEFT_WALL_OFFSET 0
#define SENSOR_SIDE_RIGHT_WALL_OFFSET 0

#define SENSOR_FRONT_LEFT_WALL_SLOPE -0.0537
#define SENSOR_FRONT_LEFT_WALL_INTERCEPT 456
#define SENSOR_FRONT_RIGHT_WALL_SLOPE -0.0532
#define SENSOR_FRONT_RIGHT_WALL_INTERCEPT 451
#define SENSOR_SIDE_LEFT_WALL_SLOPE -0.0563
#define SENSOR_SIDE_LEFT_WALL_INTERCEPT 447
#define SENSOR_SIDE_RIGHT_WALL_SLOPE -0.0529
#define SENSOR_SIDE_RIGHT_WALL_INTERCEPT 435
#endif

#define SENSOR_FRONT_CALIBRATION_DISTANCE 250
#define SENSOR_FRONT_CALIBRATION_STEP 5
#define SENSOR_FRONT_CALIBRATION_READINGS ((SENSOR_FRONT_CALIBRATION_DISTANCE / SENSOR_FRONT_CALIBRATION_STEP) + 1)
#define SENSOR_SIDE_CALIBRATION_READINGS 100
#define SENSOR_FRONT_DETECTION ((CELL_DIMENSION * 1.5))
#define SENSOR_SIDE_DETECTION ((CELL_DIMENSION * 0.9))

/** Control de inicio de competición */
#define SENSOR_FRONT_DETECTION_START 130
#define SENSOR_START_MIN_MS 150
#define SENSOR_START_MAX_MS 500

/** Divisor de Voltage */
#define VOLT_DIV_FACTOR 2.654
#define BATTERY_HIGH_LIMIT_VOLTAGE 8.4
#define BATTERY_LOW_LIMIT_VOLTAGE 7.4

/** Modo RUN */
#define CONFIG_RUN_RACE 1
#define CONFIG_RUN_DEBUG 0

void set_all_configs(void);
uint16_t get_config_run(void);

#endif