#ifndef __CONFIG_H
#define __CONFIG_H

#include <buttons.h>
#include <stdio.h>

// #define ZOROBOT3_A 1
#define ZOROBOT3_B 2
// #define ZOROBOT3_C 3

/** Laberinto */
#define CELL_DIMENSION 180
#define CELL_DIAGONAL 127.3
#define WALL_WIDTH 12
#define MIDDLE_MAZE_DISTANCE ((CELL_DIMENSION - WALL_WIDTH) / 2.)
#define SENSING_POINT_DISTANCE 0
#define WALL_LOSS_TO_SENSING_POINT_DISTANCE 106

/** Características Físicas */
#ifdef ZOROBOT3_A
#define MICROMETERS_PER_TICK 10.494055
#endif
#ifdef ZOROBOT3_B
#define MICROMETERS_PER_TICK 10.494055
#endif
#ifdef ZOROBOT3_C
#define MICROMETERS_PER_TICK 10.494055
#endif
#define ROBOT_FRONT_LENGTH 48.121
#define ROBOT_BACK_LENGTH 40.706
#define ROBOT_WIDTH 70.2
#define WHEELS_SEPARATION 62
#define ROBOT_MIDDLE_WIDTH ((ROBOT_WIDTH / 2.0))

/** Movimiento */
#define MAX_MOTOR_SATURATION_COUNT 20
#define MAX_MOTOR_ANGULAR_SATURATION_COUNT 60
#define KP_LINEAR 0.0003
#define KD_LINEAR 0.0005

#define KP_ANGULAR 0.01
#define KD_ANGULAR 0.4

#define KP_SIDE_SENSORS 0.08
#define KI_SIDE_SENSORS 0.00 // 0.002
#define KD_SIDE_SENSORS 0.12

#define KP_FRONT_SENSORS 0.02
#define KI_FRONT_SENSORS 0.00035

// #define KP_FRONT_DIAGONAL_SENSORS 0.0001
// #define KI_FRONT_DIAGONAL_SENSORS 0.00001
// #define KD_FRONT_DIAGONAL_SENSORS 0.002

#define KP_FRONT_DIAGONAL_SENSORS 0.040
#define KI_FRONT_DIAGONAL_SENSORS 0.001//0010
#define KD_FRONT_DIAGONAL_SENSORS 0.040//0010

/** Sensores */
#define SENSOR_LOW_PASS_FILTER_ALPHA 0.1

#define SENSOR_FRONT_CALIBRATION_READINGS 20
#define SENSOR_SIDE_CALIBRATION_READINGS 100
#define SENSOR_FRONT_DETECTION ((CELL_DIMENSION * 1.22))
#define SENSOR_SIDE_DETECTION ((CELL_DIMENSION * 0.7))

/** Control de inicio de competición */
#define SENSOR_FRONT_DETECTION_START 100
#define SENSOR_START_MIN_MS 350

/** Divisor de Voltage */
#ifdef ZOROBOT3_C
#define VOLT_DIV_FACTOR 5.30
#else
#define VOLT_DIV_FACTOR 3.15
#endif
#define BATTERY_2S_HIGH_LIMIT_VOLTAGE 8.4
#define BATTERY_2S_LOW_LIMIT_VOLTAGE 7.4
#define BATTERY_3S_HIGH_LIMIT_VOLTAGE 12.6
#define BATTERY_3S_LOW_LIMIT_VOLTAGE 11.1

/** Modo RUN */
#define CONFIG_RUN_RACE 1
#define CONFIG_RUN_DEBUG 0

void set_all_configs(void);
uint16_t get_config_run(void);

#endif